# ~/.dotfiles/.config/gh/config.yml

git_protocol: ssh  # Or 'https' if you prefer https cloning
editor: code         # Change to 'vim', 'nano', 'nvim', etc. if you prefer
prompt: enabled
aliases:
  co: pr checkout
  pv: pr view --web
