# 🎨 Perfect Gruvbox Starship Configuration
# Clean, functional, and beautiful - combining the best of all approaches

format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$java\
$php\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'gruvbox_dark'

# Gruvbox Dark Palette (authentic colors)
[palettes.gruvbox_dark]
# Background colors
bg0 = '#282828'      # Main background
bg1 = '#3c3836'      # Slightly lighter
bg2 = '#504945'      # Even lighter
bg3 = '#665c54'      # Light background
bg4 = '#7c6f64'      # Lighter still

# Foreground colors  
fg0 = '#fbf1c7'      # Light cream
fg1 = '#ebdbb2'      # Main text
fg2 = '#d5c4a1'      # Slightly darker
fg3 = '#bdae93'      # Even darker
fg4 = '#a89984'      # Dark text

# Accent colors
red = '#fb4934'      # Bright red
green = '#b8bb26'    # Bright green  
yellow = '#fabd2f'   # Bright yellow
blue = '#83a598'     # Bright blue
purple = '#d3869b'   # Bright purple
aqua = '#8ec07c'     # Bright aqua/cyan
orange = '#fe8019'   # Bright orange

# Muted variants
red_dim = '#cc241d'
green_dim = '#98971a'
yellow_dim = '#d79921'
blue_dim = '#458588'
purple_dim = '#b16286'
aqua_dim = '#689d6a'
orange_dim = '#d65d0e'

# Grays
gray = '#928374'
gray_dim = '#7c6f64'

# Directory styling - clean and prominent
[directory]
style = 'bold fg:yellow'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

# Clean directory substitutions (your style)
[directory.substitutions]
"Developer" = "󰲋 "
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

# Git branch - clean and readable
[git_branch]
symbol = ' '
style = 'fg:aqua'
format = '[on](fg:fg4) [$symbol$branch ]($style)'

# Git status - informative but not overwhelming
[git_status]
style = "fg:red"
format = "([$all_status$ahead_behind]($style) )"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
deleted = "✘"
modified = "!"
staged = "+"
untracked = "?"
renamed = "»"
conflicted = "="


# Git metrics - shows actual line changes (this is gold!)
[git_metrics]
added_style = 'fg:green'
deleted_style = 'fg:red'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = false

# Fill - pushes right side content to the right
[fill]
symbol = ' '

# Python - clean and informative
[python]
symbol = ' '
style = 'blue'
format = '[${symbol}${pyenv_prefix}(${version} )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

# Node.js
[nodejs]
symbol = ' '
style = 'green'
format = '[$symbol($version) ]($style)'

# Lua
[lua]
symbol = ' '
style = 'blue'
format = '[$symbol($version) ]($style)'

# Go
[golang]
symbol = ' '
style = 'aqua'
format = '[$symbol($version) ]($style)'

# Haskell
[haskell]
symbol = ' '
style = 'purple'
format = '[$symbol($version) ]($style)'

# Rust
[rust]
symbol = ' '
style = 'orange'
format = '[$symbol($version) ]($style)'

# Ruby
[ruby]
symbol = ' '
style = 'red'
format = '[$symbol($version) ]($style)'

# Java
[java]
symbol = " "
style = 'orange'
format = '[$symbol($version) ]($style)'

# PHP
[php]
symbol = " "
style = 'purple'
format = '[$symbol($version) ]($style)'

# Package version
[package]
symbol = '󰏗 '
style = 'purple'
format = '[$symbol($version) ]($style)'

# AWS
[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

# Docker - smart detection
[docker_context]
symbol = " "
style = 'blue'
format = '[$symbol$context ]($style)'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']
only_with_files = true

# Jobs - background processes
[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol$number ]($style)'

# Command duration - performance feedback
[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration ]($style)'

# Character - the prompt symbol
[character]
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vicmd_symbol = '[❮](bold fg:yellow)'

# Line break
[line_break]
disabled = false

# Additional useful modules (disabled by default)

# Time display
[time]
disabled = true
time_format = "%R"
style = 'fg:gray'
format = '[$time ]($style)'

# Memory usage
[memory_usage]
disabled = true
threshold = 70
symbol = '󰍛 '
style = 'fg:red'
format = '[$symbol$ram ]($style)'

# Battery (for laptops)
[battery]
full_symbol = '🔋'
charging_symbol = '⚡ '
discharging_symbol = '💀 '
disabled = true

[[battery.display]]
threshold = 15
style = 'bold fg:red'

[[battery.display]]
threshold = 50
style = 'bold fg:yellow'

# Status codes
[status]
style = 'fg:red'
symbol = '✖ '
format = '[\[$symbol $common_meaning$signal_name$maybe_int\] ]($style)'
map_symbol = true
disabled = false

# Kubernetes (if you use it)
[kubernetes]
format = '[⛵ $context \($namespace\) ]($style)'
style = 'fg:blue'
disabled = true

# Conda environments
[conda]
style = 'fg:green'
format = '[$symbol$environment ]($style)'
disabled = false